@extends('layouts.app', ['title' => 'Gravações | Tela do Agente - Thconect'])

@section('body')
<div class="app-shell"><x-sidebar />
    <main class="workspace admin-workspace recordings-workspace">
        <header class="page-heading"><div><p class="eyebrow">{{ ($isSupervisor ?? false) ? 'EQUIPE DA EMPRESA' : 'CENTRAL PBX' }}</p><h1>{{ ($isSupervisor ?? false) ? 'Gravações dos agentes' : 'Gravações de chamadas' }}</h1></div><a class="button button-soft" href="{{ ($isSupervisor ?? false) ? route('supervisor.dashboard') : (auth()->user()->isSuperAdmin() ? route('admin.index') : route('admin.supervision.index')) }}">{{ ($isSupervisor ?? false) ? 'Voltar ao acompanhamento' : 'Voltar à administração' }}</a></header>
        <section class="panel recordings-filter"><div class="section-title"><div><p class="eyebrow">CONSULTAR</p><h2>Filtrar gravações</h2></div></div>
            <form method="GET" class="filter-form">
                <label>De<input type="date" name="from" value="{{ $filters['from'] ?? '' }}"></label><label>Até<input type="date" name="to" value="{{ $filters['to'] ?? '' }}"></label><label>Telefone<input name="phone" inputmode="tel" value="{{ $filters['phone'] ?? '' }}" placeholder="DDD + número"></label>
                @unless($isSupervisor ?? false)<label>Empresa<select name="tenant_id"><option value="">Todas</option>@foreach($tenants as $tenant)<option value="{{ $tenant->id }}" @selected(($filters['tenant_id'] ?? null) == $tenant->id)>{{ $tenant->name }}</option>@endforeach</select></label>@endunless
                <label>Resultado<select name="status"><option value="">Todos</option>@foreach(['completed'=>'Atendida','no_answer'=>'Não atendida','busy'=>'Ocupado','voicemail'=>'Caixa de mensagens','invalid_number'=>'Número não existe','rejected'=>'Recusada','cancelled'=>'Cancelada','unavailable'=>'Indisponível','failed'=>'Não completada'] as $value=>$label)<option value="{{ $value }}" @selected(($filters['status'] ?? '') === $value)>{{ $label }}</option>@endforeach</select></label>
                <div class="filter-actions"><button class="button button-primary">Filtrar</button><a class="button button-soft" href="{{ ($isSupervisor ?? false) ? route('supervisor.recordings.index') : route('admin.recordings.index') }}">Limpar</a></div>
            </form></section>
        <section class="registry recordings-registry"><div class="section-title"><div><p class="eyebrow">ARQUIVOS DISPONÍVEIS</p><h2>{{ $recordings->total() }} gravação(ões)</h2></div><span class="muted">Somente chamadas atendidas com áudio válido são exibidas.</span></div>
            <div class="table-wrap"><table><thead><tr><th>Data</th>@unless($isSupervisor ?? false)<th>Empresa</th>@endunless<th>Ramal</th><th>Agente</th><th>Telefone</th><th>Resultado</th><th>Duração</th><th>Ouvir</th></tr></thead><tbody>@forelse($recordings as $recording) @php($call = $recording->call)<tr><td>{{ $call?->started_at?->copy()->timezone(config('app.display_timezone'))->format('d/m/Y H:i') ?? '—' }}</td>@unless($isSupervisor ?? false)<td>{{ $call?->tenant?->name ?? '—' }}</td>@endunless<td>{{ $call?->extension?->number ?? '—' }}</td><td>{{ $call?->extension?->user?->name ?? '—' }}</td><td>{{ $call?->to_number ?? $call?->from_number ?? '—' }}</td><td>{{ $call?->resultLabel() ?? '—' }}</td><td>{{ gmdate('H:i:s', (int) $recording->display_duration_seconds) }}</td><td><audio controls preload="none" src="{{ route(($isSupervisor ?? false) ? 'supervisor.recordings.play' : 'admin.recordings.play', $recording) }}">Seu navegador não suporta áudio.</audio></td></tr>@empty<tr><td colspan="{{ ($isSupervisor ?? false) ? 7 : 8 }}" class="empty-cell">Nenhuma gravação encontrada com estes filtros.</td></tr>@endforelse</tbody></table></div>
            <div class="pagination-wrap">{{ $recordings->onEachSide(1)->links('components.pagination') }}</div></section>
    </main></div>
@endsection
